### ISSUE TITLE
worekd instead worked

### ISSUE THREAD

**Issue by Futosone** [omidfi/moro#12]
I noticed this little issue in my console:

Today you **worekd**:

**Comment by omidfi** [comment]
Thanks for reporting @Futosone  I ran a gnu aspell on all the files and found 5-6 more typos :)

**Comment by Futosone** [comment]
@omidfi you're welcome, thanks for your tool :)  oh and btw the german magazine t3n wrotes an article about your tool. Good Work!  
http://t3n.de/news/kommandozeile-terminal-time-tracking-zeiterfassung-803805/

**Comment by omidfi** [comment]
Oh thanks @Futosone for the article link. I was wondering why it got 20 stars on github all of a sudden :D
