### ISSUE TITLE
Status of current working day

### ISSUE THREAD

**Issue by rwam** [omidfi/moro#15]
It would be nice to have a subcommand to get a summary of the current tracker like `moro status`:

![moro](https://cloud.githubusercontent.com/assets/2979907/23858389/82a983a0-0800-11e7-87a1-52ea26d2a744.png)

**Comment by omidfi** [comment]
@rwam 
Thanks for the nice idea. It's implemented now, just update your Moro to the latest and you will get
$ moro status

**Comment by rwam** [comment]
Hi @omidfi,

thanks a lot.

Ciao
Ralf
