### ISSUE TITLE
Conditional break substraction

### ISSUE THREAD

**Issue by fleischie** [omidfi/moro#32]
Hi,

Might it be possible to have the break be only substracted when the working hours exceed 4 hours or so? I find it very disappointing to have negative working hours between 0 and 30 minutes into the day. (I am willing to volunteer a PR, but only if you think it's ok.) 😁

Alternatively clamp the working hours to 0 if below 0?

**Comment by omidfi** [comment]
Hi @fleischie, 

Thanks for reporting the issue. 

Other users have found it strange as well, for example in the screen recording when it becomes -29 minutes.

One problem with conditionally adding breaks is that the "report --all" will be unclear. So we'll have to show break duration in there as well. 

This will be a breaking change and makes the articles about Moro outdated, at least the one written in T3N. 

By the way have you considered setting your break duration manually? 

moro break 0 

How would that sound?

**Comment by fleischie** [comment]
Hey, thanks for the quick reply.

I can certainly work around this issue. I guess it's not that grave either, as it only affects workdays with less than 30 minutes of work. :stuck_out_tongue_winking_eye:

I though this might be a larger issue and wouldn't have to many consequences, but I agree, that in this case the costs outweigh the benefits. :bowing_man:
