### ISSUE TITLE
Heart Spinner not stopping on help

### ISSUE THREAD

**Issue by fleischie** [omidfi/moro#34]
Hi, me again. :slightly_smiling_face: 

I noticed, the spinner is started before parsing the arguments to moro.js. But it is only stopped on explicit commands: hi, bye, break, report, status, config, clear.

Running `moro.js -h/--help/help` does not stop the spinner (as `process.exit(0)` is never called and the spinner is thus never stopped. At least on linux and fish/zsh, I don't know, whether this is a problem on Mac as well.

Edit: This is also a problem, when using the caporal-features `moro.js` is built on. To be specific the tab-completion functionality (`moro.js completion bash` or `moro.js completion fish`) also displays the heart-spinner indefinitly.

**Comment by omidfi** [comment]
Hi @fleischie, 

Thanks for coming by again :) 

You are right. It happens and it's due to a bug in Caporal. The bug is fixed in their master branch but it's not yet released. I'll update Moro once they release it. 

This is the PR that fixes the issue in Caporal: 
https://github.com/mattallty/Caporal.js/pull/27

It might be also a good idea to move to another alternative, something that doesn't have this exit problem and also provides a way to personalize the help section. 

Thanks again
Omid

**Comment by omidfi** [comment]
@fleischie if you're up to it a refactoring to replace caporal with yargs or Commander would be appreciated :)

**Comment by fleischie** [comment]
@omidfi yeah, sure. Any preferences? If not, I'll research some alternatives including the named ones and report back to you. 😊

**Comment by omidfi** [comment]
@fleischie  wow thanks. 
I have checked those two and both of them look good. There must be other options but the important things I can think of are:
1. the current Moro api shouldn't change. Users shouldn't learn anything new. 
2. The help page would be more awesome if we could customize it, or write it ourselves. The help page that tldr (https://github.com/tldr-pages/tldr) has is awesome. It lists all the commands, and at the end gives examples. 

Anything that you think does that would be nice and I appreciate  your help :)

**Comment by fleischie** [comment]
I researched some alternatives:
- [commander.js](https://github.com/tj/commander.js)
- [minimist](https://github.com/substack/minimist)
- [yargs](https://github.com/yargs/yargs)

minimist and commander.js seems to be a little slow on development, as the latest commits were in 2015 resp. in february 2016. yargs was last committed to 7 days ago. commander.js and yargs both allow custom help descriptions/extensions (minimist does, too, but as it's mostly manual, we would have to re-implement the --help switch on our own anyways).

At this point I am against minimist, as it's lightweight but minimal approach seems to be more work, than it is useful in this project's context (I might re-consider based on comments, thought. :slightly_smiling_face: )

yargs has more dependencies, than commander.js and I will check, whether which one has a serious impact on the final 'bundle' (I will produce a simple non-moro bundle, I don't want to threaten you with porting the build-chain to a bundler.... yet. :wink: ). If this isn't a major issue and/or both seem to be relatively "heavyweight" (in lack of a better term), my personal tendency is for yargs, as it seems to be more versatile and mature.

With both alternatives left, the requirements can be met:
1. API shouldn't change (and I am willing to write additional tests, if necessary), as only the arg-parser backend changes. I said shouldn't and would re-evaluate on this point, if it turns out, it does change.
2. Custom help pages are possible, because both allow augmenting/customizing the help-output.

That's my two cents, if you have any additional thoughts, I'm all ears. I will check back again with the weight of both libraries and afterwards begin with a first draft. :slightly_smiling_face:

**Comment by omidfi** [comment]
@fleischie wow that was a great review :) 

> my personal tendency is for yargs,
Then go for it, looks reasonable. 

I also started writing it by yargs, then found the documentation a bit complicated, so left it :) 

> I will produce a simple non-moro bundle, I don't want to threaten you with porting the build-chain to a bundler.... yet. 
We could use a bundler if need be :)

**Comment by fleischie** [comment]
I had time to implement the arg-parsing with `yargs` now and I must say: I am not as enthusiastic as I was this morning.

- I had to rewrite most of the commands, as the yargs-handler parses other arguments as caporal does.
- The argument-handling is much more verbose and manual than with caporal.
- Having a really good `help` function (as in `help` is the command with the available commands as the arguments) must be manually implemented, which is not really fun and problem-solving.
- The output must be reviewed, as the spinner breaks the intended output flow (as the first line is always occupied by something).

I suggest a quick-fix for the issue at hand: Move the spinner-starting and -stopping into the commands functions, so that help and version does not start the spinner. (Which is a much smaller PR, than replacing caporal with yargs)

Also: `yargs` seems a huge step backwards for solving the command-line problem in respect to `caporal`. I don't think it should matter that much, that moro uses high-level frameworks (like `caporal` or `vorpal`) for it's cli-basis.
AlsoAlso: `yargs` is not only complicated-ly documented, but also very complicated to fully utilize. I found myself work around the intended behavior, than use it for my advantage.

I might open the quick-fix PR tomorrow.

P.S.: It might be more sensible to re-inforce the current code-base, as replace the underlaying cmdline-framework. :man_shrugging: 
P.P.S.: It was still fun working on this project, so far. :slightly_smiling_face:

**Comment by omidfi** [comment]
@fleischie wow great findings, and nice tinkering. Highly appreciated :) 
Alright then Yargs can't help us. 
About the quick fix, there's an issue. I first put the heart spinner inside the commands, the problem with that was this: 
There was a long delay before the heart was shown. I think between the place the heart is now, and when we get to the command, there is the most time spent. So users wouldn't see anything hapenning for a long time, and then the heart showed up and quickly after that the full response was shown. 

I guess we better wait for the fix in Caporal to get released.

**Comment by fleischie** [comment]
I see you inquired the status/release on the caporal page. Should I close this issue?

Alternatively I can try porting the program to vorpal (as another Cli-Backend)? Only if you're still interested in an over-the-top fix for such a small issue. :sweat_smile:

**Comment by omidfi** [comment]
Wow that Vorpal looks interesting. Would be interesting to see how it fits. Please do so if you can ♥️

**Comment by fleischie** [comment]
OK, vorpal is cool but I guess it has a different approach to command line tools, as this project has. It is possible to start a sandboxed shell with just `moro` (for example) to start the available programs within said shell. It can be modified to one-shot start the programs, too. (So, whenever you would like to release moro 3 with an interactive moro-shell, this is a good framework. :stuck_out_tongue_winking_eye: )

The major issue still is, that `help` and `version` must be re-written by hand to bypass stalling the program because of the spinner. (vorpal doesn't exit the program as well..) This yields us with the same situation, we have at the beginning of this discussion.

I cannot believe, that the spinner is bringing everything (including myself) to it's knees. :sweat_smile:

**Comment by omidfi** [comment]
@fleischie  huh huh :D 

Ok at least I  learned a lot about different frameworks. 

Thanks a lot for your time and efforts. Let's close this issue and just wait for the fix in Caporal :)

**Comment by omidfi** [comment]
@fleischie just FYI it's solved now \o/   :D  I ended up sending a tiny to caporal

**Comment by fleischie** [comment]
Awesome. :tada:
