### ISSUE TITLE
make database file's location configurable

### ISSUE THREAD

**Issue by omidfi** [omidfi/moro#40]
so that it can be put on dropbox etc.

**Comment by fleischie** [comment]
@omidfi I was thinking about this today. Do you need help with this? :stuck_out_tongue:

**Comment by omidfi** [comment]
@fleischie help would be highly appreciated :) I've lost my own records a few times while I was developing. 

I haven't done anything for this yet. I only have some vague imaginations about how it might be: 

moro config --database-path /home/jack/moro-data.db 

There's a config.json that keeps a couple of things already, database path can be added there as well,once users change the default. We also explain that copying the original file to the new path is user's responsibility. Maybe?

**Comment by fleischie** [comment]
See PR #51 

I did not change the README as of yet, as it's (intended to be) a backwards-compatible extension of the configuration mechanism. I can still update the PR, if you want. But I wanted to present you with the current progress so far. :slightly_smiling_face:

**Comment by omidfi** [comment]
Fixed in #51 thank you @fleischie :)
