### ISSUE TITLE
Use `spinner.succeed()`/`spinner.fail()` instead of `console.log` calls

### ISSUE THREAD

**Issue by fleischie** [omidfi/moro#50]
This might tie in better with the given framework (or to be more exact the spinner), than merely writing some text to the console. :slightly_smiling_face:

**Comment by omidfi** [comment]
I totally agree. I tried to do it like that at the beginning but couldn't figure out how to pass the spinner instance around, so gave up and shipped it as soon as it worked somehow :) 

I'll get back to it whenever I can. And of course help would be appreciated :)

**Comment by fleischie** [comment]
I already started, but minimized the padding between the individual messages (because `console.log('\n')` yields in the spinner being abandoned in the current step in the console.)

I will tweak the output to be more padded (i.e. to emulate the current behavior). I keep you updated on this. :slightly_smiling_face:  :+1:
