### ISSUE TITLE
FeatureRequest

### ISSUE THREAD

**Issue by Memphizzz** [omidfi/moro#79]
Hi, 

I really would like to use moro but in its current state i can't. I need to have multiple entries per day.
I was expecting something like:

moro hi 0800.
moro task DoSomething 0845

which would create a task with a duration of 45 minutes

and

moro hi 0800
moro task DoSomething 40m

which would do the same but duration of 40 minutes

Do you have anything like this planned?

**Comment by omidfi** [comment]
Hi @Memphizzz,

Thanks for taking the time to open an issue. 

Currently I use the note taking feature for that.
moro hi
moro note DoSomethingBegan
moro note DoSomethingEnded

and in the report I get to see the notes:
[08:10] DoSomethingBegan
[08:50] DoSomethingEnded

And I calculate the duration myself. 

If you need something more flexible and automatic you can check https://github.com/samg/timetrap

**Comment by omidfi** [comment]
I close this, please reopen if it wasn't convincing.
