### ISSUE TITLE
Set the full day correctly

### ISSUE THREAD

**Issue by Isengo1989** [omidfi/moro#88]
moro config --day 8 will not set the day to 8 hours - it always tells me  "Working until  16:10 will make it a full (7.5) day " afterwards.

**Comment by omidfi** [comment]
I can't reproduce the issue on my computer. 

Could you tell me what operating system you use? What version of node? 

There should be a config file in your home directory where Moro saves it's settings:
 .moro-config.json 

Does that exist on your machine?

**Comment by Isengo1989** [comment]
@omidfi no this file does not exist. There is only .moro-data.db

I am using a MacBook Pro / macOS Sierra 10.12.5 with node V7.7.2

**Comment by omidfi** [comment]
@Isengo1989 
Sure
```
{"BREAK_DEFAULT":30,"HOURS_IN_A_WORK_DAY":8,"DATE_FORMAT":"dddd, MMMM D","DB_FILE_MAIN":"/home/GraceHopper/.moro-data.db"}
```

**Comment by Isengo1989** [comment]
I created the file in my home dir and changed the path at the end - still showing 7.5 hours tho.

**Comment by omidfi** [comment]
Sorry I can't reproduce this. But in next releases, I'll try to move this setting to database probably that makes it better.
