### ISSUE TITLE
Allow notes starting with -

### ISSUE THREAD

**Issue by erwald** [omidfi/moro#96]
Currently this doesn't seem to be possible:

```sh
✗ moro note "-5"
💛  Moro \o/
   Error: Unknown option -5.
   Type moro --help for help.
```

**Comment by omidfi** [comment]
@erwald thank you for reporting this. 

Can you help me reproduce it?
What OS are you using? What node version? 

On my ubuntu, and node 8, both of these seem to work:
```
✗ moro note "-5"
✗ moro note -5
```

**Comment by erwald** [comment]
I'm on macOS Sierra v10.12.5.

```sh
~ rbenv:(2.2.4)  node -v
v7.5.0

~ rbenv:(2.2.4)  moro note "-5"
💛  Moro \o/
   Error: Unknown option -5.
   Type moro --help for help.

~ rbenv:(2.2.4)  moro note -5
💛  Moro \o/
   Error: Unknown option -5.
   Type moro --help for help.
```

**Comment by fleischie** [comment]
I just tried with node versions 6.11.2, 7.5.0, 7.10.1 and 8.2.1. And all work with both `moro note -5` and `moro note "-5"`.

**Comment by erwald** [comment]
Seems to work now after updating to v8.4 of node, so I'll close.
